# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Model(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, kernel_version: str=None, machine_type: str=None, hw_type: object=None):  # noqa: E501
        """Model - a model defined in Swagger

        :param kernel_version: The kernel_version of this Model.  # noqa: E501
        :type kernel_version: str
        :param machine_type: The machine_type of this Model.  # noqa: E501
        :type machine_type: str
        :param hw_type: The hw_type of this Model.  # noqa: E501
        :type hw_type: object
        """
        self.swagger_types = {
            'kernel_version': str,
            'machine_type': str,
            'hw_type': object
        }

        self.attribute_map = {
            'kernel_version': 'kernel_version',
            'machine_type': 'machine_type',
            'hw_type': 'hw_type'
        }

        self._kernel_version = kernel_version
        self._machine_type = machine_type
        self._hw_type = hw_type

    @classmethod
    def from_dict(cls, dikt) -> 'Model':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Model of this Model.  # noqa: E501
        :rtype: Model
        """
        return util.deserialize_model(dikt, cls)

    @property
    def kernel_version(self) -> str:
        """Gets the kernel_version of this Model.

        output of 'uname --kernel-version'  # noqa: E501

        :return: The kernel_version of this Model.
        :rtype: str
        """
        return self._kernel_version

    @kernel_version.setter
    def kernel_version(self, kernel_version: str):
        """Sets the kernel_version of this Model.

        output of 'uname --kernel-version'  # noqa: E501

        :param kernel_version: The kernel_version of this Model.
        :type kernel_version: str
        """

        self._kernel_version = kernel_version

    @property
    def machine_type(self) -> str:
        """Gets the machine_type of this Model.

        output of 'uname --machine'  # noqa: E501

        :return: The machine_type of this Model.
        :rtype: str
        """
        return self._machine_type

    @machine_type.setter
    def machine_type(self, machine_type: str):
        """Sets the machine_type of this Model.

        output of 'uname --machine'  # noqa: E501

        :param machine_type: The machine_type of this Model.
        :type machine_type: str
        """

        self._machine_type = machine_type

    @property
    def hw_type(self) -> object:
        """Gets the hw_type of this Model.

        available kits  # noqa: E501

        :return: The hw_type of this Model.
        :rtype: object
        """
        return self._hw_type

    @hw_type.setter
    def hw_type(self, hw_type: object):
        """Sets the hw_type of this Model.

        available kits  # noqa: E501

        :param hw_type: The hw_type of this Model.
        :type hw_type: object
        """

        self._hw_type = hw_type
